specVersion: 1.0.0
name: centrifuge-pools
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '1'
  query:
    name: '@subql/query'
    version: '1'
description: 'SubQuery API powered by EMBRIO.tech to query Centrifuge chain data for analytics insights on how Centrifuge is unlocking economic opportunity for all by connecting people to borrow and lend money transparently and cost-effectively.'
repository: https://github.com/centrifuge/pools-subql
schema:
  file: ./schema.graphql
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
          filter:
            timestamp: '1 0,12 * * *'
        # - handler: logEvents
        #   kind: substrate/EventHandler
        - handler: handlePoolCreated
          kind: substrate/EventHandler
          filter:
            module: poolSystem
            method: Created
        - handler: handlePoolUpdated
          kind: substrate/EventHandler
          filter:
            module: poolSystem
            method: Updated
        - handler: handleEpochClosed
          kind: substrate/EventHandler
          filter:
            module: poolSystem
            method: EpochClosed
        - handler: handleEpochExecuted
          kind: substrate/EventHandler
          filter:
            module: poolSystem
            method: EpochExecuted
        - handler: handleInvestOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: investments
            method: InvestOrderUpdated
        - handler: handleRedeemOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: investments
            method: RedeemOrderUpdated
        - handler: handleInvestOrdersCollected
          kind: substrate/EventHandler
          filter:
            module: investments
            method: InvestOrdersCollected
        - handler: handleRedeemOrdersCollected
          kind: substrate/EventHandler
          filter:
            module: investments
            method: RedeemOrdersCollected
        - handler: handleProxyAdded
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyAdded
        - handler: handleProxyRemoved
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyRemoved
        - handler: handleProxyPureCreated
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: PureCreated
        - handler: handleLoanCreated
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Created
        - handler: handleLoanBorrowed
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Borrowed
        - handler: handleLoanRepaid
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Repaid
        - handler: handleLoanClosed
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Closed
        - handler: handleTokenTransfer
          kind: substrate/EventHandler
          filter:
            module: ormlTokens
            method: Transfer
        - handler: handleTokenEndowed
          kind: substrate/EventHandler
          filter:
            module: ormlTokens
            method: Endowed
        - handler: handleTokenDeposited
          kind: substrate/EventHandler
          filter:
            module: ormlTokens
            method: Deposited
        - handler: handleTokenWithdrawn
          kind: substrate/EventHandler
          filter:
            module: ormlTokens
            method: Withdrawn
